### ISSUE TITLE
Extension does not work out-of-the-box under Ubuntu (udev issue)

### ISSUE THREAD

**Issue by zaventh** [keepkey/chrome-proxy#9]
Chromium Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

In the extension console, I see the following errors:

```
extensions::uncaught_exception_handler:8 Error in response to hid.connect: [object Object]
    at connect (chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:31552:20)
    at Object.module.exports.onConnect (chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:31669:5)
    at chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:30783:22handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:72
extensions::lastError:133 Unchecked runtime.lastError while running hid.connect: Failed to open HID device.
    at connect (chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:31552:20)
    at Object.module.exports.onConnect (chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:31669:5)
    at chrome-extension://idgiipeogajjpkgheijapngmlbohdhjg/background.js:30783:22reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
```

Under chrome://device-log/, I see various permission-related errors:

```
[15:11:09] Failed to open '/dev/hidraw0': FILE_ERROR_ACCESS_DENIED
HIDEvent[15:11:09] Access denied opening device read-write, trying read-only.
HIDUser[15:11:09] HID device added: vendorId=11044, productId=1, name='KeepKey, LLC. KeepKey', serial='[redacted]', deviceId='/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:2B24:0001.000C/hidraw/hidraw0'
HIDUser[15:11:04] HID device removed: deviceId='/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:2B24:0001.000B/hidraw/hidraw0'
HIDEvent[15:08:05] Failed to open '/dev/hidraw0': FILE_ERROR_ACCESS_DENIED
HIDEvent[15:08:05] Access denied opening device read-write, trying read-only.
HIDEvent[14:41:30] Failed to open '/dev/hidraw0': FILE_ERROR_ACCESS_DENIED
HIDEvent[14:41:30] Access denied opening device read-write, trying read-only.
HIDUser[14:41:30] HID device added: vendorId=11044, productId=1, name='KeepKey, LLC. KeepKey', serial='[redacted]', deviceId='/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:2B24:0001.000B/hidraw/hidraw0'
HIDUser[14:41:25] HID device removed: deviceId='/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:2B24:0001.000A/hidraw/hidraw0'
```

The issue is that the device /dev/hidraw0 was restricted by default to root only by udev. Presumably because although the device is registered as a HID, it does not actually report as a keyboard or mouse, and so the default udev configuration restricts access to it. I was able to resolve this problem with the following udev rule:

``` sh
echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev", ATTRS{idVendor}=="2b24", ATTRS{idProduct}=="0001"' | sudo tee /etc/udev/rules.d/70-keepkey.rules
```

Presumably you guys will want to include some documentation to this effect in your startup guide or FAQ so as not to frustrate people needlessly.

**Comment by bruceswiney** [comment]
Hi Zaventh,

We do have documentation about running KeepKey on Linux on our support site.

Here is the link to our article: https://support.keepkey.com/solution/articles/6000037796-keepkey-wallet-is-not-being-recognized-by-linux

If you have any questions or concerns, please contact us at support@keepkey.com

Sincerely,

Bruce

**Comment by zaventh** [comment]
Ah, yes I had failed to uncover that article in my search or see the rules file in the repo actually. Although, I do think the "plugdev" group is slightly more appropriate here. At least some variants of Ubuntu no longer add users to the "dialout" group by default, which is historically used for serial comms. Also, chmodding 664 also seems to be a tiny bit more cautious so other users not in this group cannot interact with the KeepKey.
